import { z } from 'zod';

export const getOrderSchema = z.object({
  ordNbr: z.string(),
  ordDate: z.string(),
  cusId: z.string().nullable(),
  cusCode: z.string().nullable(),
  cusName: z.string().nullable(),
  address: z.string().nullable(),
  tel: z.string().nullable(),
  buyerIdentityCard: z.string().nullable(),
  email: z.string().nullable(),
  description: z.string().nullable(),
  totalAmountWithoutVat: z.number().nullable(),
  discountPercenatge: z.number().nullable(),
  totalDiscount: z.number().nullable(),
  taxAmount: z.number().nullable(),
  taxReductionAmount: z.number().nullable(),
  totalAmount: z.number().nullable(),
  cusAmount: z.number().nullable(),
  returnAmount: z.number().nullable(),
  paymentMethod: z.string().nullable(),
  orderStatus: z.string().nullable(),
  invoiceStatus: z.string().nullable(),
  invoiceNbr: z.string().nullable(),
  taxCode: z.string().nullable(),
  companyName: z.string().nullable(),
  securityNbr: z.string().nullable(),
  linkCheckInvoice: z.string().nullable(),
  invoiceType: z.string().nullable(),
  invoiceId: z.string().nullable(),
  invoiceDate: z.string().nullable(),
  invoiceSymbol: z.string().nullable(),
  totalVatAmount: z.number().nullable(),
  orderDetails: z.array(z.any()),
  bankId: z.string().nullable(),
  voucherCode: z.string().nullable(),
  warehouseId: z.string().nullable(),
  voucherOrd: z.string().nullable(),
  toWarehouseId: z.string().nullable(),
  isVat: z.boolean().nullable(),
  refId: z.string().nullable(),
  refNbr: z.string().nullable(),
  tenantId: z.string().nullable(),
  id: z.string(),
  creationTime: z.string().nullable(),
  creatorId: z.string().nullable(),
  lastModificationTime: z.string().nullable(),
  lastModifierId: z.string().nullable(),
});

export type GetOrderSchemaType = z.infer<typeof getOrderSchema>;
